### ISSUE TITLE
Genre thumbs not fully generated when poster filenames have unicode characters

### ISSUE THREAD

**Issue by MoojMidge** [sualfred/script.embuary.helper#21]
Hi,

When the genre thumbs are being created, posters with filenames including unicode characters are not correctly fetched, resulting in black spaces in the generated thumbnails.

Not sure if the files are correctly fetched if they are cached or not, however I seem to recall that this used to work without issue when the genre thumbs feature was first added.

Cheers.

**Comment by sualfred** [comment]
@MoojMidge 

Can you please test https://github.com/sualfred/script.embuary.helper/commit/c4ef22cdd75ad04240298a6733d0428bcfbcc385 ?

That should solve it.

**Comment by sualfred** [comment]
Fix is available on my repo.

**Comment by MoojMidge** [comment]
Thanks for that, fixed the issue.

One thing though - why don't you use the following bit of code:
```
image = image.encode('utf-8')
    image = url_unquote(image.replace('image://', ''))

    if image.endswith('/'):
        image = image[:-1]
```
at the start of _openimage() before the following?
```
cachedthumb = xbmc.getCacheThumbName(image)
```

At the moment the cached files are never found and used.

**Comment by sualfred** [comment]
Brain fucked. Of course you are right. Will change that.

**Comment by sualfred** [comment]
https://github.com/sualfred/script.embuary.helper/commit/6da954c5c3213e0949e6f945f967bd1df0cf8d63

**Comment by MoojMidge** [comment]
:+1:  Thanks again.
