### ISSUE TITLE
1.4.3 breaks blurring after playback is stopped.

### ISSUE THREAD

**Issue by roidy** [sualfred/script.embuary.helper#34]
https://github.com/sualfred/script.embuary.helper/commit/1bfec4eee6e9c5fec6cda00b06900d1830211a12

This commit breaks blurring after playback is stopped, please see my commit notes.

**Comment by sualfred** [comment]
Thanks. A simple "break" was missing. Fixed.

**Comment by roidy** [comment]
Could you fix this in master and not just matrix please.

**Comment by sualfred** [comment]
Forgot to push. Fix is also on the repos.

**Comment by roidy** [comment]
Thank you.
