### ISSUE TITLE
Blurring of embedded art is broken

### ISSUE THREAD

**Issue by roidy** [sualfred/script.embuary.helper#35]
I made the following commit https://github.com/sualfred/script.embuary.helper/commit/0259ac1c3278fd6ca8bc7061a6dc77d2252deb3f to fix the issue with blurring not working on embedded artwork in mp3 files. 

Since then the image functions have been reworked and blurring of embedded artwork in mp3 files is again broken :(

I think it's one of the following commits:-

https://github.com/sualfred/script.embuary.helper/commit/d4878461cd1b6926a20cc85d759a591667c02a19
or
https://github.com/sualfred/script.embuary.helper/commit/f7adf3f70a699db578ce9c29b10814d7ce12c555

**Comment by roidy** [comment]
I've trace the issue to this line:-
https://github.com/sualfred/script.embuary.helper/blob/d8636d7c91d9e56730e1f8f657e1939743554cc0/resources/lib/image.py#L233
Removing `image://` breaks embedded images.

This code change works fine:-
`image = url_unquote(image)`

**Comment by sualfred** [comment]
@roidy 
Matrix or Leia?

**Comment by sualfred** [comment]
could you also please add `log(image, force=True)` to the first line in this function so I can see how the path looks like on your end?

**Comment by roidy** [comment]
Leia.

Heres the log lines for mp3 embedded artwork, the first line is `image` at the function entry point and the second is after the unquote and replace..... This fails to get the image.

NOTICE: [ script.embuary.helper ] image://music@nfs%3a%2f%2f192.168.0.100%2fvolume1%2fMedia%2fMusic%2fAly%20%26%20AJ%2fDon%27t%20Go%20Changing%20-%20Single%2f01%20Don%27t%20Go%20Changing.mp3/

NOTICE: [ script.embuary.helper ] music@nfs://192.168.0.100/volume1/Media/Music/Aly & AJ/Don't Go Changing - Single/01 Don't Go Changing.mp3

However line removing line 233 so `image` isn't unquoted and has the `image://` part fixes the issue and embedded art loads fine.

**Comment by sualfred** [comment]
@roidy 
Unquoting is required to get valid cache filenames.

Can you confirm that this commit is fixing it?
https://github.com/sualfred/script.embuary.helper/commit/7d29e75e6ff32ffaff8a8b96fceb28fad664a853

**Comment by roidy** [comment]
I can confirm that fixes the issue, thanks.
