### ISSUE TITLE
Average color function is inaccurate

### ISSUE THREAD

**Issue by roidy** [sualfred/script.embuary.helper#36]
After some basic testing the average color function seems to be inaccurate. It could be simplified and made more accurate using the following code:-

```
img = Image.open(filepath)
img2 = img.resize((1,1), Image.ANTIALIAS)
col = img2.getpixel((0,0))
imagecolor = 'FF%s%s%s' % (format(col[0], '02x'), format(col[1], '02x'), format(col[2], '02x'))
```

Take for example the following image, I have provided color sample of the output from both your original code and the new PIL based code.
![test1](https://user-images.githubusercontent.com/4118048/77831196-a689d180-7125-11ea-9b1c-059074b94251.png)

Clearly the average color of an equal sized area of red and blue should be purple like the new code outputs, not red like the current code. While this is an extreme example and on a real world image the difference is much less noticeable, it's still there.

Not only is the new code more accurate but on an average 200x200 pixel image it runs about 30% faster in my testing.

**Comment by sualfred** [comment]
I'm happy to see a PR
