### ISSUE TITLE
Missing cast images

### ISSUE THREAD

**Issue by roidy** [sualfred/script.embuary.helper#41]
When filling a list using

`plugin://script.embuary.helper/?info=getnewshows&showall=true`

Bringing up the info dialog for a single episode item has container 50 filled with cast names, roles and images.

However bringing up the info dialog for a tv show has container 50 filled with cast names and roles but is missing images.

**Comment by sualfred** [comment]
Can you try:
https://github.com/sualfred/script.embuary.helper/commit/355249f5fd1e2088b61d2ddc0cab96d4b2ad3615 (leia)

or 

https://github.com/sualfred/script.embuary.helper/commit/0ba028a4717d59acb1e4fd56d49a305d276a8bc2 (matrix)

?

**Comment by roidy** [comment]
Tested the leia version and it works fine. 

Thank you 👍
