### ISSUE TITLE
[REQ] New combined widget

### ISSUE THREAD

**Issue by roidy** [sualfred/script.embuary.helper#42]
I have a request, would it be possible to get a new widget that combines,

In progress movies
plugin://script.embuary.helper/?info=getinprogress&type=movie

and

Next up episode
plugin://script.embuary.helper/?info=getnextup

into one widget?

Thanks

**Comment by sualfred** [comment]
In theory yes, but it cannot be sorted by last played, because the upcoming episode has no lastplayed value.  So it would be always listed at the end of the list.

**Comment by roidy** [comment]
> So it would be always listed at the end of the list

Yes, that's exactly what I need. Basically the content of both of the above widgets combined into a single widget without any extra sorting except what they already have.

So the list would basically contain:-

In progress movie 1
In progress movie 2
.......................................
In progress movie x
Next up episode 1
Next up episode 2
......................................
Next up episode x

Or to put it another way concatenate plugin://script.embuary.helper/?info=getinprogress&type=movie and plugin://script.embuary.helper/?info=getnextup

**Comment by sualfred** [comment]
Since Leia you can define multiple contents for a widget.
Just use:
```
<control type="list">
....
bla
...
<content>plugin://script.embuary.helper/?info=getinprogress&type=movie</content>
<content>plugin://script.embuary.helper/?info=getnextup</content>
</control>
```

**Comment by roidy** [comment]
Really!!! That's fantastic, I had no idea you could do that. That makes it much easier, big thanks 👍

**Comment by sualfred** [comment]
For reference
https://forum.kodi.tv/showthread.php?tid=298565&pid=2578642#pid2578642
