### ISSUE TITLE
Playlist filter for getnextup/getinprogress broken?

### ISSUE THREAD

**Issue by filigranen** [sualfred/script.embuary.helper#50]
This is using Leia and version 1.5.0, but as far as I can tell the logic hasn't changed for this for matrix ...

Probably me doing something wrong, but cannot get it to work.

Here's what I've tried:

I tried this line
```
plugin://script.embuary.helper/?info=getnextup&amp;playlist=special://skin/extras/playlists/kids_tv.xsp&amp;reload=$INFO[Window(home).Property(EmbuaryWidgetUpdate)]
```
where kids_tv.xsp contains this:
```
<?xml version="1.0" encoding="UTF-8" standalone="yes" ?>
<smartplaylist type="episodes">
    <name>kids_tv</name>
    <match>one</match>
    <rule field="path" operator="contains">
        <value>barn_tv</value>
    </rule>
</smartplaylist>
```
but I get no output.

The playlist itself works, I see the content of my barn_tv folder, but getnextup shows nothing.
If I remove the playlist filter it works.
It also works if I use a tag= filter instead.

I also tried the inprogress widget/content type for movies, but that didn't work either.
Again, using a tag works. Or no filter.

Here's a log with a tag (works as expected): https://paste.kodi.tv/egibevecas.kodi

Here's a log with the playlist filter (does not work): https://paste.kodi.tv/hadoratafu.kodi

I enabled "logging" in the script settings, not sure if that did any difference though ...
couldn't find the log saved anywhere in addon_data or such places, so let me know if there's additional info to be attached.

**Comment by sualfred** [comment]
Will check it out once I find some time. 
The filtering by playlist wasn't implemented by me and it's possible that it's a Kodi Matrix bug.

**Comment by filigranen** [comment]
I'm trying this on Leia, haven't tested on Matrix. So in that case it is a Leia bug, or both. 

I implemented a "not-tag" filter myself to fix this for my own use case, but still need to add tags to my files which is why I wanted this to work. Could implement a contains/not contains path filter now that I think of it..

Still, this function appears broken. 😋

**Comment by sualfred** [comment]
Try wrapping the playlist in '''mypath"'.

For the nextup widget it is possible that only tvshow based playlists are working, because it is based on in progress shows and not on episodes.

Just guessing, sitting in the office.
