### ISSUE TITLE
[BUG] BackgroundInterval broken

### ISSUE THREAD

**Issue by roidy** [sualfred/script.embuary.helper#54]
From the wiki under Global Backgrounds:-

```
Note: The 10s interval can be adjusted in the addon config and skinners also can override this value by using a skin setting, eg:
Skin.String(BackgroundInterval,40)
```

However in the code:-

https://github.com/sualfred/script.embuary.helper/blob/2d43ec8eb9a18b9f1bd514b741d1d7d284a24f39/resources/lib/service_monitor.py#L112-L131

The comparison is hardcoded to 10 so background_interval will only ever count up to 10 then reset to 0. Meaning the interval is always going to be 10 seconds.

**Comment by sualfred** [comment]
thx
